### ISSUE TITLE
SystemVerilog: entering infinite loop

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2730] opened 2020-11-25 15:51 UTC
input.sv:
```
interface intf (
    input in1,
    input [11:0] in2,
    output out,
    inout iout
);

logic a, b, c, d;
logic [11:0] e;

modport master (input a, b, output c, d, e);
modport slave (output a, b, input c, d, e);

endinterface : intf

interface static
```

"./ctags -o - input.sv" leads ctags  to an infinite loop.

**Comment by masatake** [comment] 2020-11-25 15:51
"make noise" reports this.

**Comment by hirooih** [comment] 2020-11-26 23:33
fixed on #2733.

Minimal input was;

`interface static`

Caused by an unexpected EOF.
There were 8 bugs which cause infinite loop due to lack of EOF check.

**Closed by hirooih** 2020-11-26 23:33 UTC
