### ISSUE TITLE
C++: problem with template function return type

### ISSUE THREAD

**Issue by delsner** [universal-ctags/ctags#3388] opened 2022-05-16 19:31 UTC
I have a problem with return types of template functions, where the C/C++ parser misses functions, if they return any non-primitive type. Do you have any idea how to circumvent or patch the problem when parsing C++ code? Thank you!

***

The name of the parser: C/C++

The command line you used to run ctags:

```
$ ctags --options=NONE --fields-all="*" --fields-c++=-{macrodef} --fields-c=-{macrodef} --fields=-Prtl --kinds-c=+p --kinds-c++=+p --output-format=json simple.cpp
```

The content of input file:

```cpp
template<typename A, typename B>
A& foo(A& bar, B const& baz)
{
    return bar;
}
```

The tags output you are not satisfied with:

```
[empty]
```

The tags output you expect:

```
{"_type": "tag", "name": "foo", "path": "simple.cpp", "line": 2, "kind": "function", "signature": "(A & bar,B const & baz)", "end": 5, "template": "<typename A,typename B>"}
```

The version of ctags:

```
$ ctags --version
Universal Ctags 5.9.0(de7fae6a), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 16 2022, 06:25:51
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_fnmatch, +gnulib_regex, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc, +optscript
```

How do you get ctags binary:

macosx binary taken from Universal-ctags/homebrew-universal-ctags project
Win32 binary taken from Universal-ctags/ctags-win32 project

----

@masatake added:

```
#include <cstddef>

template <std::size_t S>
struct M {
};

template <T>
struct M<static_cast<std::size_t>(-1)> {
};

```

The second `M` is not tagged. Maybe the input exposes the same bug.
With the fix, "removing the code block", proposed by @delsner, the second M is tagged well.
Derived from #3263.

**Comment by masatake** [comment] 2022-05-16 21:06
This one is hard to fix.

**Comment by delsner** [comment] 2022-05-17 06:15
Could you maybe elaborate why? I'm not familiar with the code base. How would you approach it?

**Comment by masatake** [comment] 2022-05-17 09:28
For a long time, detecting whether `>` is the end of a template parameter list or a greater-than operator used in the template parameter list is one of the most difficult items in the C++ parser. Many heuristics are used for detection. The issue you reported here is about the heuristics.

inputX.cpp:
```
template<typename A, typename B>
X f(void)
{
  return A();
}
```

For this input, `f` is extracted well.

inputA.cpp:
```
template<typename A, typename B>
A f(void)
{
  return A();
}
```
As you reported, `f` is not extracted.

Finding the cause of the differences between the results of two inputs is the first thing
to do to fix this issue.

```
$ ./configure --enable-debugging
$ make clean
$ make
$ ./ctags --_trace=C++ -o - inputX.cc 2> inputX.log
$ ./ctags --_trace=C++ -o - inputA.cc 2> inputA.log
$ diff inputX.log inputA.log
```

The output of the log files tells you where the heuristics are defined in the source tree.

> I'm not familiar with the code base. 

Me, too.
Many issues with the C++ parser are reported.
I have to find the time to study the parser.

**Comment by delsner** [comment] 2022-05-19 14:31
Leaving my diff here for your reference (no tests fail locally with this change):

```
diff --git a/Units/parser-cxx.r/template-nested-triangle-brackets.d/expected.tags b/Units/parser-cxx.r/template-nested-triangle-brackets.d/expected.tags
index aa5e6610..bfadd37e 100644
--- a/Units/parser-cxx.r/template-nested-triangle-brackets.d/expected.tags
+++ b/Units/parser-cxx.r/template-nested-triangle-brackets.d/expected.tags
@@ -51,17 +50,0 @@ J	input-2.hpp	/^template<typename T,int I,int J = 1 >> (1+2)> K funcI(T t)$/;"	Z
-funcJ	input-2.hpp	/^template<typename T,int I,int J = I > 2> K funcJ(T t)$/;"	f	typeref:typename:K	template:<typename T,int I,int J=I>2>
-T	input-2.hpp	/^template<typename T,int I,int J = I > 2> K funcJ(T t)$/;"	Z	function:funcJ	typeref:meta:typename
-I	input-2.hpp	/^template<typename T,int I,int J = I > 2> K funcJ(T t)$/;"	Z	function:funcJ	typeref:typename:int
-J	input-2.hpp	/^template<typename T,int I,int J = I > 2> K funcJ(T t)$/;"	Z	function:funcJ	typeref:typename:int
-funcK	input-2.hpp	/^template<typename T,int I,int J = 1 > I> K funcK(T t)$/;"	f	typeref:typename:K	template:<typename T,int I,int J=1> I>
-T	input-2.hpp	/^template<typename T,int I,int J = 1 > I> K funcK(T t)$/;"	Z	function:funcK	typeref:meta:typename
-I	input-2.hpp	/^template<typename T,int I,int J = 1 > I> K funcK(T t)$/;"	Z	function:funcK	typeref:typename:int
-J	input-2.hpp	/^template<typename T,int I,int J = 1 > I> K funcK(T t)$/;"	Z	function:funcK	typeref:typename:int
-funcL	input-2.hpp	/^template<typename T,int I,int L,int J = I > L> K funcL(T t)$/;"	f	typeref:typename:K	template:<typename T,int I,int L,int J=I> L>
-T	input-2.hpp	/^template<typename T,int I,int L,int J = I > L> K funcL(T t)$/;"	Z	function:funcL	typeref:meta:typename
-I	input-2.hpp	/^template<typename T,int I,int L,int J = I > L> K funcL(T t)$/;"	Z	function:funcL	typeref:typename:int
-L	input-2.hpp	/^template<typename T,int I,int L,int J = I > L> K funcL(T t)$/;"	Z	function:funcL	typeref:typename:int
-J	input-2.hpp	/^template<typename T,int I,int L,int J = I > L> K funcL(T t)$/;"	Z	function:funcL	typeref:typename:int
-funcO	input-2.hpp	/^template<typename T,int I,unsigned int J = 1 > (1+2)> K funcO(T t)$/;"	f	typeref:typename:K	template:<typename T,int I,unsigned int J=1> (1+2)>
-T	input-2.hpp	/^template<typename T,int I,unsigned int J = 1 > (1+2)> K funcO(T t)$/;"	Z	function:funcO	typeref:meta:typename
-I	input-2.hpp	/^template<typename T,int I,unsigned int J = 1 > (1+2)> K funcO(T t)$/;"	Z	function:funcO	typeref:typename:int
-J	input-2.hpp	/^template<typename T,int I,unsigned int J = 1 > (1+2)> K funcO(T t)$/;"	Z	function:funcO	typeref:typename:unsigned int
diff --git a/Units/parser-cxx.r/template-nested-triangle-brackets.d/input-2.hpp b/Units/parser-cxx.r/template-nested-triangle-brackets.d/input-2.hpp
index 2c9ac624..3b74e495 100644
--- a/Units/parser-cxx.r/template-nested-triangle-brackets.d/input-2.hpp
+++ b/Units/parser-cxx.r/template-nested-triangle-brackets.d/input-2.hpp
@@ -49,0 +50,3 @@ template<typename T,int I,int J = 1 >> (1+2)> K funcI(T t)
+/*
+
+Examples below are invalid C++ (see #3388)
@@ -65,0 +69,7 @@ template<typename T,int I,int L,int J = I > L> K funcL(T t)
+template<typename T,int I,unsigned int J = 1 > (1+2)> K funcO(T t)
+{
+	return 0;
+}
+
+*/
+
@@ -81,10 +90,0 @@ template<typename T,int I,unsigned long int J = I > V> K funcN(T t)
-template<typename T,int I,unsigned int J = 1 > (1+2)> K funcO(T t)
-{
-	return 0;
-}
-
-
-
-
-
-
diff --git a/parsers/cxx/cxx_parser_template.c b/parsers/cxx/cxx_parser_template.c
index 64505b37..578a971d 100644
--- a/parsers/cxx/cxx_parser_template.c
+++ b/parsers/cxx/cxx_parser_template.c
@@ -436,31 +422 @@ cxxParserParseTemplateAngleBracketsInternal(bool bCaptureTypeParameters,int iNes
-				// check greater than operator: very narrow conditions
-				if(
-					(iGreaterThanCount == 1) &&
-					(
-						// whatever op 2 [C++03 allows this without parens]
-						// whatever op (...) [C++03 allows this without parens]
-						cxxTokenTypeIsOneOf(
-								g_cxx.pToken,
-								CXXTokenTypeNumber | CXXTokenTypeOpeningParenthesis
-							) ||
-						// whatever op nonTypeParameter [C++03 allows this without parens]
-						(
-							cxxTokenTypeIs(g_cxx.pToken,CXXTokenTypeIdentifier) &&
-							cxxTokenIsPresentInTemplateParametersAsNonType(g_cxx.pToken)
-						)
-						// WARNING: don't be tempted to add a loose condition that has
-						// (!cxxTokenIsPresentInTemplateParametersAsType()) on the right.
-						// It's unsafe.
-					)
-				)
-				{
-					CXX_DEBUG_PRINT("Treating as greater-than sign");
-
-					if(cxxTokenTypeIsOneOf(g_cxx.pToken,CXXTokenTypeOpeningParenthesis))
-						cxxParserUngetCurrentToken(); // needs to be condensed
-
-					continue;
-				}
-
-
-				// check right shift operator: a bit broader conditions
```

**Comment by masatake** [comment] 2022-05-19 21:57
I'm stunned that the input is invalid. Thank you for pointing it out.
We must fix the test input first. Instead of removing the lines in the test input,
putting `(` and `)` to proper places may be better. (Task A)

`validate-input` target was introduced for detecting the broken test input like @[delsner](https://github.com/delsner) pointed out. The target verifies real language processors like gcc accept the test input or not. Though we have such a great test facility, I limited the area applying the target. I must revise the target to reduce the chances of "testing ctags for invalid input". (Task B) 

About the removing `[this if clause](https://github.com/universal-ctags/ctags/blob/14ccc3ada28740cb3333f53bf142297bd90fcede/parsers/cxx/cxx_parser_template.c#L422)`, I need more time.

At the specifying template arguments, it seems that the operator (> and >>) can be used directly. 
https://stackoverflow.com/questions/5771131/nested-templates-vs-shift-operator

I'm thinking about the impact of the removal for parsing template arguments.

**Comment by masatake** [comment] 2022-05-25 22:58
#3398 is for Task A and B.
@delsner, I fixed func{D,E,F,G,H,I,J,K,L,O} though you fixed only func{J,K,L,O} in your comment. Do you think we should/shouldn't fix func{D,E,F,G,H,I}?

For validating the input I used C++11.

**Comment by delsner** [comment] 2022-05-30 21:19
If you aim to go for C++11 support, I think the way you did it should be fine!

**Comment by masatake** [comment] 2022-05-30 21:39
> If you aim to go for C++11 support, I think the way you did it should be fine!

Thank you.

How about C++03? I want to support both C++03 and C++11.

Let's think about `funcD`.
```
const int V = 10;

typedef int K;

// This stuff is allowed by C++03
template<typename T,int I,int J = I >> 2> K funcD(T t)
{
	return 0;
}
```

The original author of the test case says this is valid C++03 input.
However, GCC -std=c++03 doesn't accept this:
```
gcc -std=c++03 d.cc
d.cc:6:54: error: default template arguments may not be used in function templates without ‘-std=c++11’ or ‘-std=gnu++11’
    6 | template<typename T,int I,int J = I >> 2> K funcD(T t)
      |                             
```

Is there a way to transform `funcD` to make it "c++03 acceptable" with keeping using `>>` operator in the template parameter list?

**Comment by masatake** [comment] 2022-05-31 21:40
> I think adding parentheses around the bitwise operation might work, i.e., <..., int J = (I >> 2)> (at least in c++11 I believe?).

I see. Thank you. "adding parentheses" is done in #3398. I will merge it in soon.

**Comment by masatake** [comment] 2022-06-07 15:42
I merged #3398.
It seems the ways to parse template ARGUMENTS in C++11 and C++03 differ.
https://github.com/universal-ctags/ctags/blob/master/Units/parser-cxx.r/instantiation2.b/input.hpp

The next step is making a pull request based on the change proposed in https://github.com/universal-ctags/ctags/blob/master/Units/parser-cxx.r/instantiation2.b/input.hpp .

**Comment by delsner** [comment] 2022-06-17 14:12
@masatake any updates on this? did you already decide, if removing the case entirely is a reasonable solution?

**Comment by masatake** [comment] 2022-06-19 06:57
If we remove the code block, we have to make the lines and comments around the block consistent. It will take time. Will you do it by yourself?

**Closed** 2022-06-26 23:31 UTC
Labels: C/C++

**Comment by delsner** [comment] 2022-06-27 06:52
Thanks for being so helpful @masatake
