### ISSUE TITLE
Windows: Building git causes 'Adding a map' error

### ISSUE THREAD

**Issue by ntrel** [universal-ctags/ctags#2242] opened 2019-10-16 16:58 UTC
Hi, I just checked out ctags and get build errors:

mk_mingw.mak:
```
Adding a map is allowed only to the language specified with --langdef: Ctags at ./misc/optlib2c line 112, <$optlibfh> line 25.
make: *** [mk_mingw.mak:67: optlib/ctags-optlib.c] Error 255
```
configure --disable-external-sort && make:
```
OPTLIB2C   optlib/cmake.c
Adding a map is allowed only to the language specified with --langdef: CMake at ./misc/optlib2c line 112, <$optlibfh> line 43.
make[2]: *** [Makefile:5584: optlib/cmake.c] Error 255
```

**Comment by masatake** [comment] 2019-10-16 22:24
Looks strange.

I would like to see the output of make with V=1:

```
configure --disable-external-sort && make V=1
```

optlib/cmake.c is translated from optlib/cmake.ctags by units/optlib2c.
On my platform (GNU/Linux), the translator is run with the following command line:
```
./misc/optlib2c optlib/cmake.ctags > optlib/cmake.c
```

I would like you to try to run the command line directly. I would like to see the output.
I assumed you don't change input file, optlib/cmake.ctags.

**Comment by ntrel** [comment] 2019-10-19 13:32
@masatake I think the error occurs in the ./autogen.sh stage, see the output here:
https://gist.github.com/ntrel/086a1f4dabbd18c2636c44cc0e315c69

**Comment by ntrel** [comment] 2019-10-19 13:34
```
$ ./misc/optlib2c optlib/cmake.ctags > optlib/cmake.c
Adding a map is allowed only to the language specified with --langdef: CMake at ./misc/optlib2c line 112, <$optlibfh> line 43.
```

**Comment by masatake** [comment] 2019-10-19 23:23
Thank you.  

Following regex pattern in misc/optlib2c:
```perl
     qr/^--langdef=([^\{]+)(((\{base=([^\{]+)\})(\{(dedicated|shared|bidirectional)\})?)?)(\{_autoFQTag\})?/, 
```
failed to pick up "CMake" from following line in optlib/cmake.ctags:

```
--langdef=CMake
```
.

As far as reading the log of autogen.sh you provided,  optlib2c picked up "RSpec" from the line:
```
--langdef=RSpec{base=Ruby}{shared}
```

So, I guess this issue is something to do with the way to recognize `{` in the regex pattern.
I extracted the code related to this issue from the script:
```perl
if ("--langdef=CMake" =~ 
        qr/^--langdef=([^\{]+)(((\{base=([^\{]+)\})(\{(dedicated|shared|bidirectional)\})?)?)(\{_autoFQTag\})?/) {
    print "picked up: " . $1;
} else {
    print "failed";
}
```
I saved this lines of code as "p.pl". and I run p.pl on my mingw64 environemnt like:
```
$ perl p.pl
```
The issue was not reproduced: I got "picked up: CMake".

**Comment by ntrel** [comment] 2019-10-22 14:44
Each time I run make it truncates a .c file in optlib/ to zero bytes. I commented out this line in mk_mingw.mak:

	$(V_OPTLIB2C) $(OPTLIB2C) $< > $@

Now I've run `git checkout optlib` and can build ctags.

**Comment by masatake** [comment] 2019-10-22 14:52
> Each time I run make it truncates a .c file in optlib/ to zero bytes.
Yes, because you got an error when running "./misc/optlib2c optlib/cmake.ctags > optlib/cmake.c" from the makefile.

> Now I've run git checkout optlib and can build ctags.

I added generated C files to the git repo for people using a platform where perl is not available.

**Comment by ntrel** [comment] 2019-10-22 14:56
> $ perl p.pl
> The issue was not reproduced: I got "picked up: CMake"

I have just run that and also get: `picked up: CMake`.

**Comment by masatake** [comment] 2019-10-22 15:18
> I have just run that and also get: picked up: CMake.
Thank you for testing. ...Very strange.

Could you try the following steps:
1. Applying the following change to misc/optlib2c.
```
diff --git a/misc/optlib2c b/misc/optlib2c
index c1cc5d6d..9b57f380 100755
--- a/misc/optlib2c
+++ b/misc/optlib2c
@@ -106,6 +106,7 @@ my $options =
 	   die "--languages can be used only for disabling a language defined with --langdef: $1";
        } ],
      [ qr/^--map-([^=]*)=\+(.*)/, sub {
+	   print "/* DEBUG: Adding a map is allowed only to the language specified with --langdef=$_[0]->{'langdef'}: $1 */\n";
 	   die "Don't use --map-<LANG>=+ option before defining the language"
 	       if (! defined $_[0]->{'langdef'});
 	   die "Adding a map is allowed only to the language specified with --langdef: $1"
```
2. Run the output of the following ommand line:
```
    $ misc/optlib2c optlib/cmake.ctags | head
```

What I got in my environment:
```
/* DEBUG: Adding a map is allowed only to the language specified with --langdef=CMake: CMake */
/* DEBUG: Adding a map is allowed only to the language specified with --langdef=CMake: CMake */
/*
 * Generated by misc/optlib2c from optlib/cmake.ctags, Don't edit this manually.
 */
#include "general.h"
#include "parse.h"
#include "routines.h"
#include "field.h"
#include "xtag.h"
```

**Comment by k-takata** [comment] 2019-10-22 16:26
Which perl do you use? What do `type -a perl` and `perl -v` show?

**Comment by masatake** [comment] 2021-09-01 19:55
I will close this. Feel free to reopen this.

**Closed by masatake** 2021-09-01 19:55 UTC
Labels: BUILDSYS|git operation|workflow|test harness
