### ISSUE TITLE
Making a "release"

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#652] opened 2015-11-03 16:38 UTC
This issue is for tracking general issue for releasing .tar.gz.

I need at least one volunteer helping me updating ctags.1. If you are interested in, talk to me, here.
If I cannot find any volunteer, I will not make a release.

**Comment by masatake** [comment] 2015-11-03 16:45
The first of all, I would like to decide the version number: 6.0 or 1.0.

If we choose 6.0, we can use 5.99.n as number for beta version.
If we choose 1.0, we can use 0.99.n as number for beta version.

I prefer 6.0 but I don't have strong opinion.

**Comment by cweagans** [comment] 2015-11-03 17:47
My thoughts:

* Use [semver](http://semver.org/)
* Start at 1.0, as this project is not Exuberant Ctags  (other projects have done it this way. Neovim just tagged 0.1.0, while vim is at 7.3 I think)
* I could possibly be interested in updating ctags.1, but for clarity and transparency, can you detail what needs done?
* If this project is going to be around long term, I think we need to get serious about creating real supported releases regularly. If it's not 100% ready for whatever reason, then let's do a 0.1.0 release or something, but let's at least get something out there.
* For packaging and distribution on different platforms, here is a possible solution:
    * **Linux distros**: OpenSuse's OpenBuildService handles all of these really really well. We can start with Fedora and Debian (and possibly a separate one for Ubuntu specifically), and then start rolling out support for other distros later.
    * **Windows**: Appveyor is free for open source projects
    * **Mac**: We already have the Homebrew packaging stuff, but it would be nice to provide "bottles" for the formula, which is essentially a pre-built formula (see [official docs](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md) for more info). We only need to do this manually if we continue maintaining our own Homebrew tap. If we can get a 1.0 release out the door, we can add the formula to the main Homebrew formula repository, and we'll automatically get pre-built binaries on 4 different versions of Mac OS. For now, though, I can provide pre-built binaries for Homebrew on the most recent release (El Capitan)
    * When a release is tagged on Github, a .tar.gz and a .zip source package will automatically be built. I think it would make a lot of sense to grab the packages from the various build services and associate them directly with the Release in Github (so that all of the binary, OS-specific packages show up in the release file list). That doesn't have to happen right away, however. I'd be happy enough just providing links to users for the right place to download things.

**Comment by liugang** [comment] 2015-11-04 09:35
There are too many ctags, is it possible to have  universal-ctags with other package name? 


$ update-alternatives --list ctags
/usr/bin/ctags-exuberant
/usr/bin/ctags.emacs24

$ dpkg -L emacs24-bin-common|grep ctags                                                                                                                                             
/usr/bin/ctags.emacs24

$ dpkg -L exuberant-ctags|grep ctags                                                                                                                                                
/usr/bin/ctags-exuberant

**Comment by viccuad** [comment] 2015-11-06 15:54
Hi, I'm packaging universal-ctags for Debian (in fact, the package is done since some weeks, and I'm just waiting for #92 to be fixed).

About using OpenSuse's OpenBuildService for providing a Debian package, it seems fine if you want to release a .deb as upstream, but for having it inside the Debian repos it seems more appropiate to package ir properly: to comply with Debian's Policy, be up-to-date on changes on the dependencies of the distro, and make use of some distro goodies, such as reproducible builds (as I have packaged it, it should be already reproducible) or:

@liugang , I don't know about other distros, but in Debian I have packaged it as universal-ctags, and the binary has as name `ctags-universal` using the provided configure flag '--program-transform-name'. Anyways, it shouldn't be a problem since in Debian you can choose from all ctags installed in the system, because we provide a chooser: `update-alternatives`.

**Comment by cweagans** [comment] 2015-11-06 15:57
I would prefer that the binary name remain as `ctags`, and have this package conflict with exuberant-ctags.

The major benefit that I see about using OBS is that we can tag a release, kick off a new build, and the update is available immediately. How does that process work for Debian? Do we just wait for you or somebody else to update it?

**Comment by vhda** [comment] 2015-11-06 16:02
@cweagans in Debian the correct way is to have different binary names per package, but all being configured as a "ctags" provider. By default Debian uses a priority list to choose which "ctags" provider will be used, but the administrator can configure it manually also if necessary.
This allows having multiple packages that provide the same binary (like bash and dash for /bin/sh) to coexist in the same environment.

@viccuad would you be willing to create a PR (at the time you find appropriate) to have the debian folder merged into our repository?

**Comment by cweagans** [comment] 2015-11-06 16:04
@vhda I see. So if somebody installs `universal-ctags`, and there are no other ctags providers, they'd still be able to just run `ctags` from their shell and `ctags-universal` would be the one that gets executed?

**Comment by vhda** [comment] 2015-11-06 16:06
@cweagans exactly!

Another example, which requires more steps than only configuring the alternatives, is having radeon and fglrx AMD graphic drivers installed at the same time in the same machine. The GLX library is provided by both Mesa and fglrx packages, with the later being the default. Nevertheless, the administrator can choose to use Mesa instead.

**Comment by cweagans** [comment] 2015-11-06 16:12
Okay, that works perfect. debian++  I knew there was a reason I liked that distro

What does the update process for an official debian package look like? 

1. We tag the release on Github
2. ?
3. ~~Profit!~~ Users can upgrade with `apt`

Just wondering what step 2 consists of.

**Comment by vhda** [comment] 2015-11-06 16:15
For that part @viccuad will need to step in.
You can read this to get more information: https://wiki.debian.org/NewQueue
And search for more hits in google regarding Debian's New Queue.

**Comment by cweagans** [comment] 2015-11-06 18:21
I created a bunch of other smaller, more focused issues. Please see https://github.com/universal-ctags/ctags/milestones/Initial%20release for the full list, and https://github.com/universal-ctags/ctags/issues/655 for the Debian packaging discussion.

**Closed by cweagans** 2015-11-06 18:21 UTC
Labels: Release blocker

**Comment by cweagans** [comment] 2015-11-06 19:02
Okie dokie. I think I'm done categorizing things now. https://github.com/universal-ctags/ctags/milestones/Initial%20release should be up to date. We're already 54% of the way to an initial release (since I also recategorized some of the already-closed issues)!

@universal-ctags/admins @universal-ctags/developers Please let me know where I can help, particularly around coordination, documentation, and packaging.

**Comment by masatake** [comment] 2015-11-08 00:30
(I got a trouble in my health.
I will catch up.)

**Comment by mcritchlow** [comment] 2017-05-14 22:41
Just wanted to 👍 this effort. Having a tagged version is the only blocker for me packaging this up for the distro/package manager I use.
