### ISSUE TITLE
I think my pkg-config (0.29) is legitimately too new.

### ISSUE THREAD

**Issue by IngwiePhoenix** [universal-ctags/ctags#3042] opened 2021-06-01 05:40 UTC
Hello!

I am currently trying to find a way to extract function, struct/union and enum definitions from C files to automate the process of generating thin wrappers for [V](https://github.com/vlang/v). So I wanted to give ctags a go and see where it goes.

Unfortunately, that adventure failed quite fast.

```
$ sh -x autogen.sh
+ set -xe
+ type autoreconf
+ type pkg-config
+ [ -z  ]
+ type make
+ MAKE=make
+ make -s -f makefiles/list-optlib2c-input.mak
+ ctags_files=optlib/RSpec.ctags
optlib/cmake.ctags
optlib/ctags-optlib.ctags
optlib/elixir.ctags
optlib/elm.ctags
optlib/gdbinit.ctags
optlib/inko.ctags
optlib/iPythonCell.ctags
optlib/kconfig.ctags
optlib/man.ctags
optlib/markdown.ctags
optlib/meson.ctags
optlib/mesonOptions.ctags
optlib/passwd.ctags
optlib/pod.ctags
optlib/qemuhx.ctags
optlib/puppetManifest.ctags
optlib/scss.ctags
optlib/systemtap.ctags
+ make -s -f makefiles/list-txt2cstr-input.mak
+ txt_files=main/CommonPrelude.ps
+ autoreconf -vfi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:33: error: must install pkg-config 0.18 or later before running ./autogen.sh
configure.ac:33: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
+ echo failed in running autoreconf
failed in running autoreconf
+ exit 1
```

I always use `-x` on `autogen.sh` files to track calls because...autotools. I don't trust them a whole lot...

Well, after reading the error message, I verified my `pkg-config` installation:

```
$ pkg-config --version
0.29
```

Looking for `pkg.m4` within `/usr/share/aclocal` was successful too, so it should be available.

Any idea how to fix this? Thank you!

**Comment by k-takata** [comment] 2021-06-01 05:55
What does `type -a aclocal` show?

**Comment by IngwiePhoenix** [comment] 2021-06-01 06:22
```
$ type -a aclocal
aclocal is /usr/local/bin/aclocal
aclocal is /usr/bin/aclocal
```

**Comment by IngwiePhoenix** [comment] 2021-06-01 07:24
The two versions are:

```
$ /usr/bin/aclocal --version
aclocal (GNU automake) 1.16.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

$ /usr/local/bin/aclocal --version
aclocal (GNU automake) 1.16.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

So only a minor difference.

**Comment by k-takata** [comment] 2021-06-01 07:30
Maybe `pkg.m4` is only installed in `/usr/share` and not installed in `/usr/local/share`?

**Comment by IngwiePhoenix** [comment] 2021-06-01 07:51
I made an edit to `autogen.sh` to explicitly include `/usr/share/aclocal` - and that fixed the issue. I... don't know why, but that seems to have done the trick. A little weird but, okay.

**Comment by IngwiePhoenix** [comment] 2021-06-01 08:10
Looks like my `local` installation was favoured.

```
$ /usr/bin/aclocal --print-ac-dir
/usr/share/aclocal

$ /usr/local/bin/aclocal --print-ac-dir
/usr/local/share/aclocal
```

So, this was definitively a "me" problem - but a hidden one, nontheless.

Is it possible to make autoreconf try the system installed version first, before trying the user installed one?

**Comment by masatake** [comment] 2021-06-01 12:23
Do you think this is a bug of the build-script of u-ctags?

**Comment by k-takata** [comment] 2021-06-01 12:46
I think that the issue is that aclocal is installed in /usr/local but pkg-config is not installed in /usr/local, and the build script detects as expected that pkg-config is not installed.

**Comment by masatake** [comment] 2021-06-01 13:13
> I think that the issue is that aclocal is installed in /usr/local but pkg-config is not installed in /usr/local, and the build script detects as expected that pkg-config is not installed.

Do you mean it is better for our autogen.sh to compare the installation paths, $(which aclocal) and $(which pkg-config)?

**Comment by IngwiePhoenix** [comment] 2021-06-01 13:24
Actually:

```shell
aclocal_dir=$(dirname $(which aclocal))
autoreconf_dir=$(dirname $(which autoreconf))
if [ ! "$aclocal_dir" = "$autoreconf_dir" ]; then
  autoreconf_flags="-I/usr/share"
fi
```

If both tools are seen from different locations, include the system-default path as a failsafe, maybe?

**Comment by k-takata** [comment] 2021-06-01 13:28
@IngwiePhoenix You should compare aclocal and pkg-config, not autoreconf.
@masatake I'm not sure if we need to add such check.

**Comment by masatake** [comment] 2021-06-01 14:00
> @masatake I'm not sure if we need to add such check.

I see. Thank you. Such check may reduce the numbers of this kind of issues. However, I think it is overkill.
A person who installs two set of autotools should know what can happen.

However, knowing the root cause of building-failure in early is good for us. I will introduce the following change:
```
diff --git a/autogen.sh b/autogen.sh
index 633b771b6..7497690e7 100755
--- a/autogen.sh
+++ b/autogen.sh
@@ -1,7 +1,9 @@
-#!/bin/sh
+o#!/bin/sh
 
 set -xe
 
+tools="autoreconf pkg-config"
+
 type autoreconf > /dev/null 2>&1 || {
 	echo "No autotools (autoconf and automake) found" 1>&2
 	exit 1
@@ -58,4 +60,13 @@ else
 	exit 1
 fi
 
+set +x
+echo '#'
+echo '# The paths for tools'
+echo '#'
+for t in $tools; do
+	type $t
+done
+set -x
+
 exit $?
```

**Comment by leleliu008** [comment] 2021-06-01 18:01
I don't think this problem is a bug. 

two version of `automake` is installed in user's system, in this case are `/usr/local` and `/usr`. when run the command `autoreconf -ivf`, the `aclocal` command will be invoked. the `aclocal` command is provided by `automake` package, it will search *.m4 files. the search logical is [here](https://www.gnu.org/software/automake/manual/html_node/Macro-Search-Path.html). the `/usr/local/bin/aclocal` will search `/usr/local/share/aclocal`, the `/usr/bin/aclocal` will search `/usr/share/aclocal`, For some reasons, `pkg.m4` is not installed in `/usr/local/share/aclocal` so , `pkg.m4` is not found by `aclocal` command. 

`aclocal` compare with autoconf and pkg-config all are not correct. because the `aclocal` command search *.m4 logical is nothing to do with them.

we can not add '-I /usr/share/aclocal', because `-I /usr/share/aclocal` take precedence over the default search path.

Actually, the `aclocal` search *.m4 path is usually handle by package manager. we don't need to do extra work.

**Closed** 2021-06-03 08:47 UTC

**Comment by masatake** [comment] 2021-06-03 08:49
I think `includinng the system-default path as a failsafe` is overkill. We should keep autogen.sh small.
