### ISSUE TITLE
namespace as structure member name throws C parser off

### ISSUE THREAD

**Issue by vladak** [universal-ctags/ctags#1299] opened 2017-02-07 12:54 UTC
**Test file:**

```
#ifdef	__cplusplus
extern "C" {
#endif

typedef struct foo_s {
	char *foo;
	char *namespace;
} foo_t;

typedef struct bar_s {
	char *bar;
} bar_t;

#ifdef	__cplusplus
}
#endif
```

**ctags version**:

```
$ ./ctags --version
Universal Ctags 0.0.0(1d3dbc8), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Feb  7 2017, 13:35:30
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +option-directory, +coproc, +xpath, +json, +interactive
```

**actual result from universal ctags**

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/1d3dbc8/
foo	foo.h	/^	char *foo;$/;"	m	struct:foo_s	typeref:typename:char *
foo_s	foo.h	/^typedef struct foo_s {$/;"	s
```

**exuberant ctags**

```
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Apr 11 2012, 01:48:44
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```

**actual result from exuberant ctags**

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.8	//
bar	foo.h	/^	char *bar;$/;"	m	struct:bar_s
bar_s	foo.h	/^typedef struct bar_s {$/;"	s
bar_t	foo.h	/^} bar_t;$/;"	t	typeref:struct:bar_s
foo	foo.h	/^	char *foo;$/;"	m	struct:foo_s
foo_s	foo.h	/^typedef struct foo_s {$/;"	s
foo_t	foo.h	/^} foo_t;$/;"	t	typeref:struct:foo_s
```

**Comment by masatake** [comment] 2017-02-07 16:29
This issue is also known as https://github.com/universal-ctags/ctags/issues/930 .

`.h` is handled by C++ parser by default:
```
[yamato@master]~/var/ctags-github% ./ctags --list-maps
...
C        *.c
C++      *.c++ *.cc *.cp *.cpp *.cxx *.h *.h++ *.hh *.hp *.hpp *.hxx *.inl *.C *.H *.CPP *.CXX
...
```

Using ``--language-force=C`` is one of solution.

I cannot find any good solution for this issue.

**Comment by vladak** [comment] 2017-02-07 17:03
Perhaps use 'extern C' as a hint to switch C  parser ?

**Comment by vladak** [comment] 2017-02-07 17:04
More heuristics would definitely help, namespace has distinct syntax.

**Comment by masatake** [comment] 2017-02-08 00:05
> Perhaps use 'extern C' as a hint to switch C parser ?

Very interesting idea! I have never think about this.
@pragmaware, how do you think about this approach?

I'm thinking about using promiseAPI (http://docs.ctags.io/en/latest/internal.html#promise-api).

**Comment by masatake** [comment] 2017-02-10 16:39
```
[jet@localhost ctags]$ cat /tmp/foo.cpp
extern "C" {

struct s {
	char *namespace;
};

}
[jet@localhost ctags]$ gcc -c /tmp/foo.cpp
/tmp/foo.cpp:4:8: error: expected unqualified-id before ‘namespace’
  char *namespace;
        ^~~~~~~~~
/tmp/foo.cpp:4:7: error: expected ‘;’ at end of member declaration
  char *namespace;
       ^
/tmp/foo.cpp:4:8: error: expected unqualified-id before ‘namespace’
  char *namespace;
```

It seems that c++ compiler rejects code using a keyword as an indentifier even if in extern "C" block.

**Comment by masatake** [comment] 2017-02-10 16:48
experimental code works well:

```
[jet@localhost ctags]$ cat /tmp/bar.h
#ifdef	__cplusplus
extern "C" {
#endif

typedef struct foo_s {
	char *foo;
	char *namespace;
} foo_t;

typedef struct bar_s {
	char *bar;
} bar_t;

#ifdef	__cplusplus
}
#endif
[jet@localhost ctags]$ ./ctags -o - --language-force=C++ --extra=+s --fields=+l /tmp/bar.h
ctags: Warning: --extra option is obsolete; use --extras instead
bar	/tmp/bar.h	/^	char *bar;$/;"	m	language:C	struct:bar_s	typeref:typename:char *
bar_s	/tmp/bar.h	/^typedef struct bar_s {$/;"	s	language:C
bar_t	/tmp/bar.h	/^} bar_t;$/;"	t	language:C	typeref:struct:bar_s
foo	/tmp/bar.h	/^	char *foo;$/;"	m	language:C	struct:foo_s	typeref:typename:char *
foo_s	/tmp/bar.h	/^typedef struct foo_s {$/;"	s	language:C
foo_t	/tmp/bar.h	/^} foo_t;$/;"	t	language:C	typeref:struct:foo_s
namespace	/tmp/bar.h	/^	char *namespace;$/;"	m	language:C	struct:foo_s	typeref:typename:char *
```

C++ parser detects `extern "C" {...}` as C language area; and schedules running C parser as a guest parser for the area. C parser accepts `namespace`, a keyword of C++ language as an identifier and tags it well.

HOWEVER, a real C++ compiler rejects such code as I wrote in the previous comment.

I will make a pull request. However, our C++/C parser maintainer may be i busy. So this will not be solved quickly.

**Comment by masatake** [comment] 2017-02-10 17:16
See #1303.

**Comment by codebrainz** [comment] 2017-02-10 18:01
> It seems that c++ compiler rejects code using a keyword as an indentifier even if in extern "C" block.

It makes sense, it's not valid C++ code. The test code in the original issue is only valid C code, it doesn't even make sense to have the `#ifdef __cplusplus` because if it's being compiled as C++ it's not valid code anyway.

**Comment by masatake** [comment] 2017-02-10 18:19
Following may be the way to go, I think:
```
    When finding a keyword at unexpected place, C++ parser throws away tag entries collected from the current input and runs C parser instead.
```

(selector may not solve this issue because C and C++ has too similar syntax.)

**Comment by b4n** [comment] 2017-02-10 21:15
> Perhaps use 'extern C' as a hint to switch C parser ?

IMO it doesn't really make sense.  Using `extern "C"` suggests you're inside C++ code, and as mentioned above, it's not valid C++ to use keywords like this.  So as @codebrainz said I only see it fixing cases that are somewhat wrong anyway.  If the author really has an `extern "C"` and C++ keywords, something's fishy anyway.
And actually, seeing `extern "C"` would rather be a hint it's C++, not C :)

IMO, the parser should rather try and detect some obvious cases where it wasn't C++ and switch to C in these cases.  The simplest solution might be retry as C if parsing a C++ yielded an obvious syntax error.

It surely is tricky, but as said IMO the fix proposed here will only ever fix handling code that has a problem in the first place: either the author should stop using C++ keywords, or she could drop the C++ guards that are effectively useless.

**Comment by pragmaware** [comment] 2017-02-10 22:51
`extern "C"` is a C++ construct. And it does not say that whatever is in the block is C code but that it has C linkage, which refers to functions and variables. C++ code is still perfectly valid within an extern "C" block so switching parsers is not a good idea.

Problems with "namespace" and "class" as keywords could be addressed by switching these keywords off in certain contexts.

**Comment by masatake** [comment] 2017-02-10 23:46
> Problems with namespace and class as variable names within headers could be addressed by switching these keywords off in certain contexts.

See cxx-keywords-as-c-identifiers.b.

**Comment by pragmaware** [comment] 2017-02-11 03:08
Yep, that unit test is quite hard to fix completly. However with #1304 I have greatly improved the output. Now typedefs and structures with C++ names are extracted and the parser does not bail out when C++ keywords are found in unexpected places but C++ language wasn't confirmed yet. This has some room for improvement but the complexity cost increases, so not sure if it's a good idea pushing it to the end.

**Comment by b4n** [comment] 2017-02-11 08:57
> This has some room for improvement but the complexity cost increases, so not sure if it's a good idea pushing it to the end.

Agreed. While supporting all valid C and C++ cases is important, it might be wise to be cautious not to add too many workarounds, not to end up with an unmaintainable parser piled with interleaved hacks.
It's highly unfortunate C++ stole the `.h` extension from C, and that people actually use that, but we have to live in such a world.  So we switched to parsing `.h` as C++ by default, because there is a lot more cases where parsing C++ as C would give bad results than the contrary; especially as many (library) developers are careful to keep their headers valid C++ so that they can be used from there.

So, in the end IMO it's a good idea to do what's reasonably possible in the parser, but if it ends up being too much trouble, maybe it'd be worth either calling it a day, or making the C++ parser bail out on obviously invalid syntax in headers, and retry the whole thing as C.  It'd be slower and all, possibly a bit annoying to implement still (as I guess full bail out isn't here already), but probably less likely to riddle the code with weird hacks.

**Comment by masatake** [comment] 2017-02-12 15:34
> making the C++ parser bail out on obviously invalid syntax in headers, and retry the whole thing as C.

I prefer this retry approach if it can make the code of C++ parser simpler.
If the slowness is serious issue, the user should use `--language-force=C`.

**Closed** 2017-02-20 21:52 UTC
