### ISSUE TITLE
Failed to open file with unicode name longer than 5

### ISSUE THREAD

**Issue by TroyDanielFZ** [universal-ctags/ctags#3015] opened 2021-05-07 15:16 UTC
```
ctags --options=NONE 比较长的测试文件.cpp
```
The file is encoded in cp936, and when the filename is short as `文件.cpp` or long ascii name, it works well. 
However, when the filename is in unicode, it fails. Sometimes for3,4 or longer names.
I can figure out why, and this maybe a bug?

**Comment by k-takata** [comment] 2021-05-07 15:21
Looks like a duplicate of #3014.

**Closed by k-takata** 2021-05-07 15:21 UTC
