### ISSUE TITLE
crash on parsing malform verilog file

### ISSUE THREAD

**Issue by kcwu** [universal-ctags/ctags#624] opened 2015-10-12 17:23 UTC
How to reproduce:
```
$ echo -e 'function\xde::0'  > crash.verilog
$ ./ctags.20151012.afl crash.verilog
Segmentation fault
```
***update: should be ```./ctags.20151012.afl --language-force=verilog crash.verilog```***

gdb stack
```
#0  0x00007ffff7a60a03 in _IO_vfprintf_internal (s=s@entry=0x7254c0, format=<optimized out>, ap=ap@entry=0x7fffffffdc28) at vfprintf.c:1661
#1  0x00007ffff7b1e565 in ___fprintf_chk (fp=0x7254c0, flag=1, format=<optimized out>) at fprintf_chk.c:35
#2  0x0000000000407c44 in addExtensionFields (tag=0x7fffffffde00) at main/entry.c:886
#3  writeCtagsEntry (tag=0x7fffffffde00) at main/entry.c:1009
#4  writeTagEntry (tag=0x7fffffffde00) at main/entry.c:1116
#5  0x0000000000408cd5 in makeTagEntry (tag=0x7fffffffde00) at main/entry.c:1189
#6  0x00000000004d945f in createTag (token=0x784a20) at parsers/verilog.c:600
#7  0x00000000004d2210 in processFunction (token=<optimized out>) at parsers/verilog.c:786
#8  findTag (token=0x784a20) at parsers/verilog.c:1046
#9  0x00000000004c9aa0 in findVerilogTags () at parsers/verilog.c:1148
```

this is found by afl-fuzz

**Comment by vhda** [comment] 2015-10-12 18:14
In what commit was this run on?

**Comment by vhda** [comment] 2015-10-12 18:19
An in what type of machine?

**Comment by kcwu** [comment] 2015-10-12 18:40
with latest commit aa2547a62353462becabe918c5ed63f4e0bc15f9
on ubuntu 14.04 64 bits,
compiled with clang 3.6

**Comment by vhda** [comment] 2015-10-12 19:46
Currently away from pc. Could you try with gcc?

**Comment by b4n** [comment] 2015-10-12 19:53
Can't reproduce neither with GCC 5.2.1 nor CLang 3.6.2 on Debian x86-64, and Valgrind doesn't report any issue either.

**Comment by kcwu** [comment] 2015-10-13 00:36
sorry, i gave wrong file extension in my bug description. it should be crash.v or with --language-force=verilog

**Comment by masatake** [comment] 2015-10-13 00:55
Reproduced.

**Comment by masatake** [comment] 2015-10-13 01:07
```
(gdb) p tag->extensionFields.scopeKind
$4 = (const kindOption *) 0x65e7d0 <VhdlKinds+16>
print sizeof (VerilogKinds)/sizeof (VerilogKinds [0])
$5 = 9
```

`tag->extensionFields.scopeKind` proints the 16th element of VhdlKinds.
Though, the number of the elements of the array is 9.

In other hands that of  SystemVerilogKinds is 19.

```
(gdb) print sizeof (SystemVerilogKinds)/sizeof (SystemVerilogKinds [0])
$6 = 19
```

**Comment by vhda** [comment] 2015-10-14 08:52
Fixed in #634

**Comment by vhda** [comment] 2015-10-14 13:43
Fix merged.

**Closed by vhda** 2015-10-14 13:43 UTC
