### ISSUE TITLE
KeyError: ''getpwuid(): uid not found: 1931032762''

### ISSUE THREAD

**Issue by triebelf** [universal-ctags/ctags#3123] opened 2021-08-18 10:27 UTC
The version of ctags:
```
❯ ctags --version
Traceback (most recent call last):
  File "<string>", line 3, in <module>
KeyError: 'getpwuid(): uid not found: 1931032762'
Universal Ctags 5.9.0(e8457b50), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jun 18 2021, 19:20:21
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +packcc, +optscript
```
You can already see the error there, because this is an active directory group, I believe ctags cannot resolve it to a proper name.

Also, this happens for any input file or option, for example from vim/gutentags:

```
gutentags: Scanning buffer 'git/.gitconfig' for gutentags setup...
gutentags: No specific project type.
gutentags: Setting gutentags for buffer 'git/.gitconfig'
gutentags: Generating missing tags file: /home/ftr8fe/.cache/gutentags/home-ftr8fe-.dotfiles-tags
gutentags: Generating wildignore options: /home/ftr8fe/.cache/gutentags/_wildignore.options
gutentags: Running: ['/home/ftr8fe/.dotfiles/vim/.vim/pack/config/start/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', '/home/ftr8fe/.cache/gute
ntags/home-ftr8fe-.dotfiles-tags', '-p', '/home/ftr8fe/.dotfiles', '-o', '/home/ftr8fe/.dotfiles/vim/.vim/pack/config/start/vim-gutentags/res/ctags_recursive.o
ptions', '-x', '@/home/ftr8fe/.cache/gutentags/_wildignore.options', '-l', '/home/ftr8fe/.cache/gutentags/home-ftr8fe-.dotfiles-tags.log']
gutentags: In:      /home/ftr8fe/.dotfiles
Press ENTER or type command to continue
gutentags: [job stdout]: 'Locking tags file...'
gutentags: [job stdout]: 'Running ctags on whole project'
gutentags: [job stdout]: 'ctags -f "/home/ftr8fe/.cache/gutentags/home-ftr8fe-.dotfiles-tags.temp" "--options=/home/ftr8fe/.dotfiles/vim/.vim/pack/config/start
/vim-gutentags/res/ctags_recursive.options"  --exclude=@/home/ftr8fe/.cache/gutentags/_wildignore.options "/home/ftr8fe/.dotfiles"'
gutentags: [job stderr]: 'Traceback (most recent call last):'
gutentags: [job stderr]: '  File "<string>", line 3, in <module>'
gutentags: [job stderr]: 'KeyError: ''getpwuid(): uid not found: 1931032762'''
gutentags: [job stderr]: 'ctags: cannot open option file "/home/ftr8fe/.dotfiles/vim/.vim/pack/config/start/vim-gutentags/res/ctags_recursive.options" : Permis
sion denied'
gutentags: Finished ctags job.
gutentags: ctags job failed, returned: 1
```

This might be a solution: https://stackoverflow.com/questions/45708449/keyerror-getpwuid-uid-not-found-381206

**Comment by triebelf** [comment] 2021-08-18 10:35
well it seems to be fixed with this version:
```
❯ ctags --version
Universal Ctags 5.9.0(p5.9.20210815.0), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 18 2021, 12:33:06
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +xpath, +yaml, +packcc, +optscript
```

**Comment by masatake** [comment] 2021-08-18 13:19
Do you mean the bug is fixed in p5.9.20210815.0?
If the answer is yes, could you close this?

**Comment by triebelf** [comment] 2021-08-18 18:43
yes, issue seems to be fixed with newer version.

**Closed** 2021-08-18 18:43 UTC

**Comment by masatake** [comment] 2021-08-18 18:58
If the issue is reproduced, please show the output of  `ctags --options=NONE --version` and `ctags --options=NONE --verbose --version` instead of `ctags --version`.  

```
❯ ctags --version
Traceback (most recent call last):
  File "<string>", line 3, in <module>
KeyError: 'getpwuid(): uid not found: 1931032762'
Universal Ctags 5.9.0(e8457b50), Copyright (C) 2015 Universal Ctags Team
```

This output is quite strange. ctags doesn't run python internally or doesn't link with 'libpython.so' or something.
But 
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
...
```
is a frament of backtrace reported by python.
It means `ctags` you run is a wrapper command running `Universal ctags`.

I wonder what kind of platform you are using.
If you use GNU/Linux + bash, the combination I'm familiar with, `type` command may help you:
```
$ type ctags
ctags is /usr/bin/ctags
$ file /usr/bin/ctags
/usr/bin/ctags: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=877506a82a6f15ff9cf32222ba874d38b96d230f, for GNU/Linux 3.2.0, stripped

$ alias ctags=mywrapper-ctags
$ type ctags
ctags is aliased to `mywrapper-ctags'
```
