### ISSUE TITLE
c++ parsing error

### ISSUE THREAD

**Issue by tuarba** [universal-ctags/ctags#1750] opened 2018-05-11 12:13 UTC
(If you will report an issue about the result of parsing,
fill the following items. If you get the input file somewhere,
write the URL or something.)

*****

The name of the parser:
c++
The command line you used to run ctags:
ctags -o tags bad.h
The content of input file:
```c++
#define int0 int
template <int,
         class _Comp0=less<int>,
         class _Comp1=less<pair<int, int> > >
class Test : public set<int> {
  typedef int xxx;
};
#define int1 int
```

The tags output you are not satisfied with:
```
int0	bad.h	/^#define int0 /;"	d
```
The tags output you expect:
```
Test	bad.h	/^class Test : public set<int> {$/;"	c
int0	bad.h	1;"	d
int1	bad.h	8;"	d
xxx	bad.h	/^  typedef int xxx;$/;"	t	class:Test
```
 This is what Exuberant Ctags generates

**Comment by tuarba** [comment] 2018-05-11 13:55
Not sure if this matters, but here is my ctags --version:
Universal Ctags 0.0.0(744610c), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 11 2018, 13:33:26
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory

**Comment by masatake** [comment] 2018-05-11 14:12
Could you run Universal-crags with following command line?
```
ctags --options=NONE -o tags bad.h
```

**Comment by tuarba** [comment] 2018-05-11 23:58
Here is what I got:

**Comment by b4n** [comment] 2018-05-12 01:31
I can confirm the issue. @masatake your input file doesn't have the same line 3, because GitHub ate the `<int>` on that line.  If you add it back, you get @tuarba's behavior.

So this means that it's the line 3's `<int>` part that confuses the C++ parser for some reason.

**Comment by masatake** [comment] 2018-05-12 01:37
@b4n, thank you. Reproduced here. I have to update issue our issue template to let a report use tipple quotes for preformatting.

**Comment by masatake** [comment] 2018-05-12 01:43
@pragmaware, could you look at this issue?

I've tried to minimize the reproducer. However, I cannot make it enough small.

```C++
template <class _Comp0=less<float>,
          class _Comp1=less<pair<long, double> > >
class Test : set<int> {
  char c;
};
```

**Comment by pragmaware** [comment] 2018-05-12 03:02
Template nastiness... hell of corner cases. This is one of the hard bits.
I've got a fix for this case but it breaks the parser-cxx.r/less-than-operator-between-anglebrackets.d unit test, which is harder to fix and has been handled with some "tricks".

Food for thoughts.

How to figure out that the second `<` in 

`template<char i, bool B = i < 10>    void f1(void) { } ...`

is actually an operator an not a template angle bracket?

**Comment by masatake** [comment] 2018-05-12 03:25
```
template<char i, bool B = i < 10> void f1(void) { } ...
```

How does a real compiler handle this?
It looks ambiguous syntax for me.

**Comment by pragmaware** [comment] 2018-05-12 03:54
It is one of the test cases we have. The compiler knows that i is a variable and not a (template) type, because it's declared just before... but in theory it could be defined anywhere else.

**Comment by codebrainz** [comment] 2018-05-12 17:29
> How does a real compiler handle this?

One trick I've seen to make such things simpler to parse is to preprocess the tokens and insert special disambiguation tokens, like say the tokens were:

```
...
TEMPLATE 
LEFT_ANGLE 
IDENTIFIER 
IDENTIFIER 
COMMA
IDENTIFIER
IDENTIFIER
EQUAL
IDENTIFIER
LEFT_ANGLE
INTEGER
RIGHT_ANGLE
...
```

You scan the tokens looking for `template<` and then count `<` and `>` openings and closings and inject some tokens like:

```
...
TEMPLATE_START*
IDENTIFIER
IDENTIFIER
COMMA
IDENTIFIER
IDENTIFIER
EQUAL
IDENTIFIER
LEFT_ANGLE
INTEGER
TEMPLATE_END*
...
```

`*` = synthetic token, replacing original token(s)

Of course it's a dirty hack, and doesn't help with truly ambiguous stuff like this:

```c+++
a < b > c;
```

Where it's literally impossible to whether it's an expression statement comparing `a` less-than `b` greater-than `c` or a variable declaration `c` of type `a` templated on `b`, without first resolving all of the type names. The joys of a crappy grammar :smile:

**Comment by masatake** [comment] 2018-05-23 16:48
The input is recorded as a test case triggering the bug.  See #1756.

**Closed** 2018-06-06 01:53 UTC
Labels: Parsers/c-c++
