### ISSUE TITLE
Ruby/RSpec parsing hangs, then killed by Out Of Memory

### ISSUE THREAD

**Issue by ivanbrennan** [universal-ctags/ctags#3306] opened 2022-03-13 16:21 UTC
I was running ctags on an RSpec test suite and found a scenario where it hangs, consuming more and more memory until the system finally kills it due to OOM (exit code 137).

I've reduced it to a minimal reproducible example with two files, a.rb and b.rb, and running:
```
$ ctags --options=NONE a.rb b.rb
```

The content of a.rb
```ruby
RSpec.describe "A" do
  describe "a" do
    it "hangs" do
      {
        for: nil
      }
      {
        for: nil
      }
    end
  end
end
```

The content of b.rb
```ruby
RSpec.describe "B" do
end
```

I tried several variations, and ctags ran successfully in every one of the following scenarios:
- swap the order of file arguments (i.e. `ctags --options=NONE b.rb a.rb`)
- process each file in a separate invocation (i.e. `ctags --options=NONE a.rb && ctags --options=NONE b.rb`)
- rename either of the `for` keys in a.rb to `foo`
- collapse either of the hashes in a.rb to a single line (i.e. `      { for: nil }`)
- remove RSpec from the equation (e.g. changing `RSpec.describe` to `Foo.describe`)

I'm attaching a log file I created by running:
```
$ strace -o strace.log ctags --options=NONE a.rb b.rb
```
[strace.log](https://github.com/universal-ctags/ctags/files/8240099/strace.log)

The version of ctags:

```
$ ctags --version
Universal Ctags 5.9.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +json, +interactive, +packcc, +optscript
```

How do you get ctags binary:
Using the nix package manager, on NixOS.
https://github.com/NixOS/nixpkgs/blob/3e072546ea98db00c2364b81491b893673267827/pkgs/development/tools/misc/universal-ctags/default.nix

**Comment by masatake** [comment] 2022-03-13 18:00
Thank you for reporting.

As you observed, this bug is something to do with the way to handle "foo". The ruby parser assumes `for` is a keyword making a block. However, the parser doesn't know "foo:" doesn't make a block. As the result scope links between tags make a circular structure. The structure triggers the OOM killer when ctags emit the tags.

What I have to do is:
A.  making the Ruby parser reject `for` in `for:` as a keyword, and
B. making the output routines detect the circular structure and skip printing it.

**Comment by ivanbrennan** [comment] 2022-03-13 18:38
@masatake Thanks for the quick response. Out of curiosity, do you know why the bug doesn't occur when processing the problematic file individually (`ctags --options=NONE a.rb`)?

**Comment by masatake** [comment] 2022-03-13 19:08
@ivanbrennan, good question.
I have not got the answer for it yet but I doubt the following code:

parsers/ruby.h:
```ruby
struct sRubySubparser {
	subparser subparser;
	/* Returning other than CORK_NIL means the string is consumed. */
	int (* lineNotify) (rubySubparser *s, const unsigned char **cp);
	void (* enterBlockNotify) (rubySubparser *s, int corkIndex);
	void (* leaveBlockNotify) (rubySubparser *s, int corkIndex);
	/* Privately used in Ruby parser side. */
	int corkIndex;
};
```
parsers/rspec.c:
```ruby
struct sRSpecSubparser {
	rubySubparser ruby;
	int scope;
};
...
extern parserDefinition* RSpecParser (void)
{
	static struct sRSpecSubparser rspecSubparser = {
		.ruby = {
			.subparser = {
				.direction = SUBPARSER_BASE_RUNS_SUB,
			},
			.lineNotify = lineNotify,
			.enterBlockNotify = enterBlockNotify,
			.leaveBlockNotify = leaveBlockNotify,
		},
		.scope = CORK_NIL,
	};

```

`corkIndex` of `sRubySubparser` and `scope` of `rspecSubparser` is not re-initialized when processing a new file
though it should be re-initialized. 

I have to add one more item to the list:
C. ruby parser must re-initialize `corkIndex` field(s) of its sub parser(s).
D. RSpec parser must re-initialize `scope` field of rspecSubparser instance.

It seems you found more than 3 bugs at once.
The issue is so critical. So I make a pull request for A and B first.

**Comment by masatake** [comment] 2022-03-13 20:14
I found C is not needed. D is the bug both a.rb and b.rb are needed for reproducing.
D may be fixed in ([033cdb0](https://github.com/universal-ctags/ctags/pull/3307/commits/033cdb03d5cd1c0f115a4804dc685b1fb948f611)).

**Closed** 2022-03-14 20:32 UTC

**Comment by masatake** [comment] 2022-03-14 20:34
Thank you for the well-investigated bug report. 
Feel free to reopen this issue if #3307 doesn't fix this issue.

**Comment by ivanbrennan** [comment] 2022-03-14 21:18
#3307 Fixed the issue for me. Thanks!
